[project]
name = "datasette-svk-layout"
version = "0.5.0"
description = "Datasette-plugin med layout, databas-typsystem och admin-UI för Svenska kyrkan"
readme = "README.md"
authors = [{name = "Henrik Vitalis"}]
license = "Apache-2.0"
classifiers=[
    "Framework :: Datasette"
]
requires-python = ">=3.9"
dependencies = [
    "datasette>=1.0a0"
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/svkau/datasette-svk-layout"
Changelog = "https://github.com/svkau/datasette-svk-layout/releases"
Issues = "https://github.com/svkau/datasette-svk-layout/issues"
CI = "https://github.com/svkau/datasette-svk-layout/actions"

[project.entry-points.datasette]
svk_layout = "datasette_svk_layout"

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio"]

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools]
packages = ["datasette_svk_layout", "datasette_svk_layout.data", "datasette_svk_layout.static", "datasette_svk_layout.templates"]

[tool.setuptools.package-data]
datasette_svk_layout = ["static/*", "templates/*", "data/*"]

